import Head from "next/head"
import Image from "next/image"
import PassedAwayUser from "../components/PassedAwayUser"
import styles from "../styles/Home.module.css"
import CardGroup from "react-bootstrap/CardGroup"

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="p-4 flex justify-center ">
                <PassedAwayUser
                    tokenURI={"fdsfds"}
                    LastWrodsManagerAddress={"fdsfds"}
                    owner={"465"}
                />
            </div>
        </div>
    )
}
